" Invoke vim-plug
" Install via:
"
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"
call plug#begin('~/.vim/plugged')

Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-rails'
Plug 'mtscout6/vim-cjsx'
Plug 'briancollins/vim-jst'
Plug 'skammer/vim-css-color'
Plug 'vim-scripts/hexHighlight.vim'
Plug 'vim-airline/vim-airline'
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tpope/vim-commentary'
Plug 'ctrlpvim/ctrlp.vim'

call plug#end()

" VIM specific settings
set nowrap
set mouse=a
set number
syntax on
filetype plugin indent on
filetype on
filetype indent on

" Auto-commands
autocmd FileType ruby setlocal expandtab shiftwidth=2 tabstop=2
autocmd FileType eruby setlocal expandtab shiftwidth=2 tabstop=2

" For NERDTree
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
" autocmd StdinReadPre * let s:std_in=1
" autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" This sets a buffer at line 80, and will automatically put new lines for
" anything that goes past line 80.
let &colorcolumn=join(range(81,81),",")
highlight ColorColumn ctermbg=235
set tw=80
set ruler

" Key-maps
nnoremap <C-a> <Home>
nnoremap <C-e> <End>
nnoremap <silent> <C-n> :NERDTreeToggle<CR>
nnoremap <silent> <C-m> :NERDTreeFind<CR>
